language: go

services:
        - postgresql

addons:
        postgresql: "9.5"

script:
        - go test -v -coverprofile=coverage.out ./...

after_succes:
        - go get github.com/schrej/godacov
        - godacov -t $GO_CODACY_TOKEN -r ./coverage.out -c $TRAVIS_COMMIT

go:
        - 1.9.x
