language: go

services:
        - postgresql

before_script:
        - go get github.com/schrej/godacov
        - psql -c 'create database course_db;' -U postgres

script:
        - go test -v -coverprofile=coverage.out ./...
        - godacov -t $GO_CODACY_TOKEN -r ./coverage.out -c $TRAVIS_COMMIT

go:
        - 1.9.x
